name: bias-audit
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - scipy
  - faker
  - python-dateutil
  - pip:
    - google-genai
    - google-generativeai
    - python-dotenv
    - ollama
    - streamlit
    - plotly
    - -e .
